# Generated by Django 4.1.2 on 2022-10-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=30)),
                ('dosage', models.CharField(choices=[('Drop', 'Drop'), ('Injection', 'Injection'), ('Vial', 'Vial'), ('Pill', 'Pill'), ('Tablet', 'Tablet'), ('Diff Form', 'Different Form')], max_length=30)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'weekly'), ('Monthly', 'monthly')], max_length=30)),
                ('occurence', models.CharField(choices=[('Once per frequency', 'once'), ('Twice per frequency', 'twice'), ('Thrice per frequency', 'thrice'), ('custom use', 'custom')], max_length=30)),
            ],
        ),
    ]
