# Generated by Django 4.1.2 on 2022-10-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_medicine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.AddField(
            model_name='medicine',
            name='first_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_name',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
