# Generated by Django 4.1.2 on 2022-10-14 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0004_medicine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
